name = "scripture-memory"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "scripture-memory"
database_id = "ef894297-d95a-4df9-bccf-3ac6be4c1cc7"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "scripture.wpsteward.com/*"
zone_name = "wpsteward.com" 