name = "scripture-memory"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[build]
command = "cd frontend && npm run build"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "scripture-memory"
database_id = "ef894297-d95a-4df9-bccf-3ac6be4c1cc7"

[vars]
ENVIRONMENT = "development"

[[routes]]
pattern = "scripture.wpsteward.com/*"
zone_name = "wpsteward.com"

[env.production]
vars = { 
  ENVIRONMENT = "production",
  SENDY_API_KEY = "",
  SENDY_LIST_ID = "",
  SENDY_URL = ""
}

[env.development]
vars = { 
  ENVIRONMENT = "development",
  SENDY_API_KEY = "",
  SENDY_LIST_ID = "",
  SENDY_URL = ""
} 