name = "scripture-memory"
main = "src/index.ts"
compatibility_date = "2024-02-20"

# Environment variables
[vars]
ENVIRONMENT = "development"

[env.production]
name = "scripture-memory"
ENVIRONMENT = "production"

[env.production.vars]
ENVIRONMENT = "production"

# Production routes
[[env.production.routes]]
pattern = "scripture.wpsteward.com/*"
zone_name = "wpsteward.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "scripture-memory"
database_id = "ef894297-d95a-4df9-bccf-3ac6be4c1cc7"
migrations_dir = "migrations"

# Production assets
[env.production.assets]
directory = "../frontend/dist"

[env.development]
name = "scripture-memory-dev"
ENVIRONMENT = "development"
API_URL = "http://localhost:8787"

[env.development.vars]
ENVIRONMENT = "development"

[[env.development.d1_databases]]
binding = "DB"
database_name = "scripture-memory-dev"
database_id = "d2e6214f-b924-47ee-a138-025dcf9c8256"
migrations_dir = "migrations"

# Development assets
[env.development.assets]
directory = "../frontend/dist" 