name = "scripture-memory-preview"
main = "src/index.ts"
compatibility_date = "2024-02-20"

# Environment variables
[vars]
ENVIRONMENT = "preview"

# Allow AWS SES endpoint
allowed_hosts = ["email.*.amazonaws.com"]

[env.preview]
name = "scripture-memory-preview"
ENVIRONMENT = "preview"
API_URL = "http://localhost:8787"

[env.preview.vars]
ENVIRONMENT = "preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "scripture-memory-preview"
database_id = "d2e6214f-b924-47ee-a138-025dcf9c8256"
migrations_dir = "migrations" 