name = "scripture-memory"
main = "src/index.ts"
compatibility_date = "2024-02-20"

# Environment variables
[vars]
ENVIRONMENT = "development"
SENDY_URL = "https://mail.wpsteward.com"
SENDY_API_KEY = "PpQYQF4pBaFKHg24Kyc0"
SENDY_LIST_ID = "X45GzUe763763892Spykdvtf2OhQ"
MARKETING_ENABLED = "true"
MARKETING_DEFAULT_OPT_IN = "false"
NODE_ENV = "development"
NOTIFICATIONS_ENABLED = "false"

[env.production]
name = "scripture-memory"
ENVIRONMENT = "production"

[env.production.vars]
ENVIRONMENT = "production"
SENDY_URL = "https://mail.wpsteward.com"
SENDY_API_KEY = "PpQYQF4pBaFKHg24Kyc0"
SENDY_LIST_ID = "z0AKz6SK2OkruQ9cgt172Q"
MARKETING_ENABLED = "true"
MARKETING_DEFAULT_OPT_IN = "false"
NODE_ENV = "production"
NOTIFICATIONS_ENABLED = "true"

[[env.production.d1_databases]]
binding = "DB"
database_name = "scripture-memory"
database_id = "ef894297-d95a-4df9-bccf-3ac6be4c1cc7"
migrations_dir = "migrations"

# Allow AWS SES endpoint
allowed_hosts = ["email.*.amazonaws.com"]

[env.development]
name = "scripture-memory-dev"
ENVIRONMENT = "development"
API_URL = "http://localhost:8787"

[env.development.vars]
ENVIRONMENT = "development"
SENDY_URL = "https://mail.wpsteward.com"
SENDY_API_KEY = "PpQYQF4pBaFKHg24Kyc0"
SENDY_LIST_ID = "X45GzUe763763892Spykdvtf2OhQ"
MARKETING_ENABLED = "true"
MARKETING_DEFAULT_OPT_IN = "false"
NODE_ENV = "development"
NOTIFICATIONS_ENABLED = "false"

[[env.development.d1_databases]]
binding = "DB"
database_name = "scripture-memory-dev"
database_id = "d2e6214f-b924-47ee-a138-025dcf9c8256"
migrations_dir = "migrations" 