name = "scripture-memory"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "scripture-memory-dev"
database_id = "d2e6214f-b924-47ee-a138-025dcf9c8256"

[vars]
ENVIRONMENT = "development" 